### ISSUE TITLE
ISOCode tlh missing

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/glottolog#101]
The ISOcode `tlh` is missing. It is currently in the [ISO-639-3 specification](http://www-01.sil.org/iso639-3/documentation.asp?id=tlh). There is a somewhat active [speech community of 20-30 speakers](https://en.wikipedia.org/wiki/Klingon_language)

**Comment by SimonGreenhill** [comment]
(ok, I admit I was trolling, but there is an (Artificial language section)[http://glottolog.org/resource/languoid/id/arti1236])

**Comment by d97hah** [comment]
Thx added for next update

2017-07-05 13:01 GMT+02:00 Simon J Greenhill <notifications@github.com>:
