### ISSUE TITLE
Update Kachama-Ganjule

### ISSUE THREAD

**Issue by mettaazh** [clld/glottolog#106]
Currently, Glottolog shows Kachama-Ganjule as spoken on Gidicho (a.k.a. Aruro) Island in Lake Abaya, Ethiopia.  In fact what is spoken on that island is Haro, a dialect or variety of what I guess should be called Kachama-Ganjule-Haro, which I guess is a dialect group in Ta-Ne Omotic > Ometo > East Ometo.  See Wolde-Mariam 2015:2-3:  Kachama and Ganjule are mutually intelligible with Haro (at least Haro speakers can understand the others), and are "spoken by people who used to live on the neighboring islands" (p. 2).

Reference:  Wolde-Mariam, Hirut. 2015. A Grammar of Haro. (LWM 505.)  Munich: Lincom Europa.

Johanna Nichols

**Comment by d97hah** [comment]
Ok I've changed the name to Kachama-Ganjule-Haro for next version. all the
best, H

2017-08-02 18:40 GMT+02:00 mettaazh <notifications@github.com>:
