### ISSUE TITLE
Vanuatu dots and name comments from Miriam

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog#107]
Miriam Meyerhoff says:

_the dot for N(e)thalp is probably too far west. I thought it was spoken on the point at the east. But Benjamin Touati’s Sorbonne PhD has a good map of the dialects in the Champagne Beach/Sakao Island area. It’s online. I also don’t know why the map has ’turtal bay’ [sic] in the middle of Santo island. Turtle Bay is a small bay on the eact coast. The big bay opening to the north is called Big Bay (or I think the Bay of Sts Peter and James, in old maps)._

**Comment by HedvigS** [comment]
Said map: https://www.academia.edu/25579196/The_initial_vowel_copy_in_the_Sakao_dialect_of_Wanohe_Espiritu_Santo_

**Comment by d97hah** [comment]
Thanks I've fixed the coordinates for Nethalp (as well as Ngen which was
also a little off). Not much to do about Turtal Bay since that seems to
come from leaflets rather than Glottolog.

2017-08-03 2:19 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment]
Cool cool cool.
