### ISSUE TITLE
Computerized assignment of lgcode error

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog#109]
There's been a few errors due to lgcode assigned from "compendious". Among them, this ref

Tattam, Henry. 1830. A compendious grammar of the Egyptian language as contained in the Coptic and Sahidic dialects, with observations on the Bashmuric; together with alphabets and numerals in the hieroglyphic and enchorial characters. London: J. & A. Arch.

Has been marked as being about Fijian. I'd suggest just re-checking all refs that have "(computerized assignment from "compendious")" in the lgcode field.

**Comment by d97hah** [comment]
Thanks, fixed for next version

2017-08-11 5:18 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by xflr6** [comment]
Fixed in fbe9c1d8125dcf6680c588fa8a6794883e015ee3
