### ISSUE TITLE
Escape single quotes within language labels in Newick trees

### ISSUE THREAD

**Issue by murawaki** [clld/glottolog#118]
The current Newick tree file (http://glottolog.org/static/download/tree-glottolog-newick.txt) contains quoted labels like 'Dzu'oasi [dzuo1238]'.

According to http://evolution.genetics.washington.edu/phylip/newick_doc.html,
single quote characters in a quoted label are represented by two single quotes.
So the correct quoted label would be 'Dzu''oasi [dzuo1238]'.

**Comment by xrotwang** [comment]
Thanks for catching this.

Note to self: Requires a small fix in https://github.com/clld/glottolog/blob/1cdf4921dada9c4cf0fa8279a2a315de4672ae25/pyglottolog/languoids.py#L102-L103
