### ISSUE TITLE
Western Mari map coordinates are wrong 

### ISSUE THREAD

**Issue by Trondtr** [clld/glottolog#120]
Both Hill (Western) and Meadow (Easter) Mari (ISO: mrj, mhr) are spoken in the Mari Republic. In addition, Eastern Mari is spoken in Bashkorstan. On the Omniglot map, Meadow Mari is (correctly) located in the Mari Republic, but Western Mari is not marked in the republic, only in Siberia.

This placement confuses an otherwise neat map of the Uralic languages.

**Comment by d97hah** [comment]
Thanks Trond, I've fixed the Hill Mari coordinate for next version! H

2017-08-27 9:38 GMT+02:00 Trond Trosterud <notifications@github.com>:

**Comment by xflr6** [comment]
Fixed in 373c53a77bd56f2834bd80932d8c89174de2f3bb
