### ISSUE TITLE
misspelling of Najamba

### ISSUE THREAD

**Issue by HeathJeffrey** [clld/glottolog#134]
"Najanga-Kindige" is a typo for "Najamba-Kindige" (bond1248). Your entry shows dialect subcategories "Nadjamba" and "Kindjim" which I (as a Dogon specialist) have been writing "Najamba" and "Kindige" (or French style "Kindigué"). You might add "Bondum Dom (narrow sense)" as a third dialect subcategory, most relevant to the Borko and Timtim zone on the Dogon plateau who do not use "Najamba" or "Kindige" for their own speech. "Bondum Dom (broad sense)" includes all dialects, but it is not widely used except by outsiders, usually in the form Bondu So.

**Comment by d97hah** [comment]
Thanks, I've fixed that for next version

2017-10-13 19:28 GMT+02:00 HeathJeffrey <notifications@github.com>:

**Comment by xflr6** [comment]
Fixed by c80028b6a048f72f67cb9058056e2192e2acfeec
