### ISSUE TITLE
Donno So distinct from Tommo So (Dogon)

### ISSUE THREAD

**Issue by HeathJeffrey** [clld/glottolog#135]
Current Glottolog nomenclature is "Tommo-Donno So Dogon' (donn1238) at language level, with subdivisions (dialects) Donno So (donn1239) and Tommo So (tomm1242). Laura McPherson published a grammar of Tommo So (MGL), and I have recently electronically published a grammar of Donno So (LDH). (At the moment the Donno So grammar is down because of a glitch at LDH that I expect to be repaired soon.) 

Laura and I agree that Tommo So and Donno So are distinct languages. At Laura's request, Ethnologue separated them in 2011. Laura (laura.emcpherson@gmail.com) messaged me today in response to my request for language I could pass on to you:

"Tommo So forms a dialect continuum, with the dialects spoken on the north end of the plateau mutually unintelligible with Donno So, while those closer to Bandiagara have more inter comprehension. Donno So is in some ways a mixed language, with Tommo So nominal system and Toro So's verbal system. From a cultural standpoint, Tommo So is considered one of the core Dogon languages, with many Dogon songs sung in Tommo So regardless of the spoken language of that community. The fact that Donno So is the language with the original ISO code rather than Tommo So is a historical accident based on the missionary attention it received in the 1960s in Bandiagara."

I personally wouldn't go so far as to call Donno So a mixed language, but it does have (naturally) some affinities to its neighbors, Toro So and Dogul Dom as well as Tommo So. I spent a few days surveying villages in the boundary zone between Tommo So and Donno So, and the local people clearly distinguish the two (using various names for Donno So).

**Comment by d97hah** [comment]
Ok if (some varieties of) Tommo So are not intelligible with (some
varieties) of Donno So we'll split them (I've done so for next Glottolog
version). This hasn't been said before in the literature.

2017-10-13 19:41 GMT+02:00 HeathJeffrey <notifications@github.com>:

**Comment by xflr6** [comment]
Fixed by c80028b6a048f72f67cb9058056e2192e2acfeec
