### ISSUE TITLE
Missing ISO 639-3 in languoid.csv

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog#138]
The language Bom-Kim that has the Glotto_id "bomk1234" should have the ISO 639-3 code "bmf" in the hid column in the download file ["languoid.csv" ](http://glottolog.org/static/download/glottolog-languoid.csv.zip).

I noticed this as I was pairing up the current Grambank sample to the sample of societies that are coded for EA033 in D-place. When matching by ISO 639-3 Bom-Kim was  sometimes the only match because it didn't have a value and was matched to other Grambank languages that didn't have a value in the ISO 639-3 column.

**Comment by xflr6** [comment]
IIRC the `hid` field is not exactly the same as the ISO 639-3 code (but a derived identifier used by Harald): [bomk1234](http://glottolog.org/resource/languoid/id/bomk1234) is linked to [bmf](http://www-01.sil.org/iso639-3/documentation.asp?id=bmf)

**Comment by xflr6** [comment]
@xrotwang maybe we want to adapt the [code that creates the download](https://github.com/clld/clld/blob/327003596f242c4c890975b2306a5e5b3b6c0e5b/clld/web/adapters/download.py#L65) within `glottolog3` for the next release (include more identifiers)?

**Comment by xrotwang** [comment]
I'm on the fence about enhancing the downloads. I'd rather spend time and energy on making the repository and its API the default way to interact with Glottolog data.

**Comment by d97hah** [comment]
In my files bomk1234 is linked to "bmf". To link dialects to glottocodes
would do violence on the notions of id and linking. The obvious solution if
one wants this functionality for dialects is indeed to look successively up
the tree.

2017-10-27 4:30 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by xrotwang** [comment]
In the repos it is linked as well:
```
# -*- coding: utf-8 -*-
[core]
name = Bom-Kim
level = language
iso639-3 = bmf
...
```

**Comment by HedvigS** [comment]
Ok, cool I'm glad it's linked everywhere else.

I'm not suggesting doing massive changes and putting lots of effort in, I was merely noting that in the file "languoid.csv", which is quite a practical file, there is a column that looks like it contains ISO 639-3 and that on one line the code for Bom-Kim is "missing" and that it should by all accounts be "bmf". I noticed this when doing things with Grambank and D-place, but there may very well be more examples of rows in "hid" that can easily be filled by a ISO 639-3.

Can you all see that that value for that row is NULL in that file?

I know that Robert is on the fence on this issues, it's come up several times and I realise that I must become an annoyance. I should be using the CLDF-formatting directly, but I still don't really understand it to be honest. I look at glottolog-contribution-clf.csv and the classification in newick and I don't really understand what those formats gains me that looking up the pk values in languoids.csv doesn't.. Clearly I must be out of my depth and perhaps I should just not be doing this at all..

I must confess, I don't understand all that is going on here and I'm a bit confused. It seems to me that rendering a file that looks almost exactly as "languoid.csv" does now, but with 

* updates to the "hid" column in accordance with the rest of the data (you can skip that if you want, I can just merge it with glottolog-contribution-clf.csv, but for other users who don't know that "hid" isn't exactly iso 639-3 that might be a good idea because it isn't communicated that this isn't ISO 639-3)
* "Glottolog_id" renamed to "Glottocode" 
* "safe" changed to "safe/unknown status" in the column for the status according to UNESCO atlas of languages in danger.

is enough. I don't know what other enhancements @xflr6  had in mind, but I can't think of any.

**Comment by HedvigS** [comment]
And frankly, those three things I can do myself but it seems unnecessary that I should sit on a personal improved copy that would be useful to other users too. That's the reason that I submitted an issue, to improve the dataset for more users. But perhaps that's a mistaken idea and I'm the only one who would care.

**Comment by xrotwang** [comment]
Regarding the missing iso code, all I meant to say Is, since it is correct
in the repos it will be correct on the website after the next release.
Sorry if that was unclear. But this also highlights why people may want to
use the repos directly: it has the most up-to-date data.

Am 28.10.2017 03:18 schrieb "Hedvig Skirgård" <notifications@github.com>:

**Comment by HedvigS** [comment]
For now, I've merged files in such a way that I have a file that is what I want, and relying on the iso 639-3 codes from glottolog-contribution-clf.csv instead of "hid" and deriving dialects, genus, dialect father, subfamily and top-genetic names & codes etc. 

If the web app is going to continue deriving languoid.csv (which I would think is a good idea), then please remove "hid" and replace it with a correct column with ISO 639-3 codes.

**Comment by HedvigS** [comment]
Thanks @xflr6

**Comment by xflr6** [comment]
We will have more columns in the pending `3.1` release. Here  is what the download would look like with the current version: [glottolog-languoid.csv.zip](https://github.com/clld/glottolog/files/1460809/glottolog-languoid.csv.zip)
