### ISSUE TITLE
Assigned ref fails to show up under assigned lg

### ISSUE THREAD

**Issue by d97hah** [clld/glottolog#179]
Glottolog has the following:

http://glottolog.org/resource/reference/id/423169
Castro, Damaris. 2010. The noun phrase in Boruca: studying a recently extinct language. STUF - Language Typology and Universals 63. 196-220. Stockholm Germany: Akademie Verlag GmbH.

it is (correctly) computer-assigned but  doesn’t mention it under Boruca:

http://glottolog.org/resource/languoid/id/boru1252

**Comment by xflr6** [comment]
Seems like documented behaviour of the `glottolog3` import (no ca-assignments for entries that are only in `degryuter` or `benjamins`), see #42 (close?):

https://github.com/clld/glottolog3/blob/dcd6ae1215ae30cde1404f4123c93cbb28bf3206/glottolog3/initdb.py#L374-L392

There are currently a handful of (manual/copied) `lgcode =` fields in `degruyter.bib`: To preserve these, we would need to move the 'opt-out of automated language assignment'-functionality here if it is still wanted (probably also cleaner).

**Comment by d97hah** [comment]
Ah yes I had forgotten. Let's keep it like it is now. I may find time for a
language-assignment facelift at some point though. all the best, H

2018-01-08 11:45 GMT+01:00 Sebastian Bank <notifications@github.com>:
