### ISSUE TITLE
Resolve crossrefs in bibfiles

### ISSUE THREAD

**Issue by xflr6** [clld/glottolog#185]
Via `crossref`, bibtex entries like  `incollection` can pull in fields from a parent entry (referenced via bibkey).
Currently, we ignore the field to prevent unresolvable references in `monster.bib`:
https://github.com/clld/glottolog/blob/0779cec0a924f377f3a005b49084a4c7ffac4d48/pyglottolog/references/bibfiles_db.py#L28
At some point, we might want to either
- resolve the crossrefs directly in our bibfiles as a one-off operation (copy the wanted fields from parent)
- add proper cross-ref-inlining support to our code in `pyglottolog/references`

Affects a small number of entries:
```sql
SELECT e.filename,
  (SELECT value FROM VALUE WHERE filename = e.filename AND bibkey = e.bibkey
   AND field = 'ENTRYTYPE') AS entrytype,
  count(*) AS n
FROM entry AS e JOIN value AS v ON v.filename = e.filename AND v.bibkey = e.bibkey
WHERE v.field ='crossref'
GROUP BY e.filename, entrytype

filename   |entrytype     |n   |
-----------|--------------|----|
bowern.bib |inbook        |2   |
bowern.bib |incollection  |247 |
bowern.bib |inproceedings |1   |
gj.bib     |incollection  |12  |
sn.bib     |incollection  |42  |
sn.bib     |unpublished   |1   |
```

**Comment by d97hah** [comment]
I vote to pull from parent one-off

2018-01-16 13:48 GMT+01:00 Sebastian Bank <notifications@github.com>:
