### ISSUE TITLE
Dialects under bookkeeping languoids (move?)

### ISSUE THREAD

**Issue by xflr6** [clld/glottolog#187]
We check that languoids under [book1242](http://glottolog.org/resource/languoid/id/book1242) are leaf nodes in the tree (formerly/downstream [here](https://github.com/clld/glottolog3/blob/8949095c23fdcc180b2cb158c35f9d052afbaa2d/glottolog3/scripts/check_db_consistency.py#L203-L204)):
https://github.com/clld/glottolog/blob/25c7878bff274f00e5f65102896454f30e4f6dac/scripts/treedb.py#L845-L847
There are 15 fails currently (all with dialects, it seems): Do we move them or is this okay for dialects?
```
id                                                |level    |name           |path              |
--------------------------------------------------|---------|---------------|------------------|
http:/glottolog.org/resource/languoid/id/adab1235 |language |Adabe          |book1242/adab1235 |
http:/glottolog.org/resource/languoid/id/calo1235 |language |Calo           |book1242/calo1235 |
http:/glottolog.org/resource/languoid/id/chor1275 |language |Chorotega      |book1242/chor1275 |
http:/glottolog.org/resource/languoid/id/fore1268 |language |Forest Maninka |book1242/fore1268 |
http:/glottolog.org/resource/languoid/id/gowl1241 |language |Gowli          |book1242/gowl1241 |
http:/glottolog.org/resource/languoid/id/guaj1255 |language |Guajajára      |book1242/guaj1255 |
http:/glottolog.org/resource/languoid/id/laur1249 |language |Laura          |book1242/laur1249 |
http:/glottolog.org/resource/languoid/id/ndak1242 |language |Ndaktup        |book1242/ndak1242 |
http:/glottolog.org/resource/languoid/id/nisi1239 |language |Dafla          |book1242/nisi1239 |
http:/glottolog.org/resource/languoid/id/norr1243 |language |Norra          |book1242/norr1243 |
http:/glottolog.org/resource/languoid/id/nucl1668 |language |Katukína       |book1242/nucl1668 |
http:/glottolog.org/resource/languoid/id/puto1237 |language |Putoh          |book1242/puto1237 |
http:/glottolog.org/resource/languoid/id/talu1239 |language |Talur          |book1242/talu1239 |
http:/glottolog.org/resource/languoid/id/vatr1237 |language |Vatrata        |book1242/vatr1237 |
http:/glottolog.org/resource/languoid/id/yamp1243 |language |Yamphe         |book1242/yamp1243 |
```

**Comment by d97hah** [comment]
It's ok if languages under book1242 have dialects. Those dialects are also
for bookkeeping only and do not id real dialects in the world.

2018-01-17 14:07 GMT+01:00 Sebastian Bank <notifications@github.com>:

**Comment by xflr6** [comment]
Thanks, updated the check accordingly (https://github.com/clld/glottolog/commit/0ca7a97300f707b794bea93efb673f1eed9b9599)

**Comment by xflr6** [comment]
On a second thought, the rationale might have been to have a flat [book1242](http://glottolog.org/resource/languoid/id/book1242) (discarding the information under which language a dialect was). AFAIU, we will get dialects directly under it in case we ever want to regard a dialect but not its language as 'not real'.

Flat would allow to identify/handle its members here without resorting to transitivity (or denormalizing top-level family of each languoid as we do in `glottolog3`), any thoughts @xrotwang?

**Comment by xrotwang** [comment]
I think it makes sense to have dialects under bookkeeping as well, and also to keep the structure under bookkeeping flat. My understanding is that we put everything under bookkeeping, that may have been used as identifiers in actual language documentation/description. That's why we don't keep obsolete group nodes. And keeping it flat is motivated by the idea that we only want to keep the reference - not any other postulated facts about the non-existing stuff, such as classification.
