### ISSUE TITLE
Polynesian names changes

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog#200]
Could the main name for Penrhyn [penr1237] be changed to Māngarongaro? It's what speakers use.

I have recently befriended Akevai (Sally) Nicholas, she's a linguist from Cook Islands who work in Auckland, and wrote PhD thesis on Soutern Cook Island Māori. She advised both that Penrhyn is better referred to as "Māngarongaro" and that a better name for Rarotongan [raro1241] is "Southern Cook Island Māori" since it covers a language variety that spans more islands than the island of just Rarotonga. Using Rarotongan becomes confusing since it's also the name for the dialect spoken on that specific island, and it makes the other islands invisible.

I know you have all kinds of considerations when it comes to names. I offer this information to you, do with it as you wish. I'll send her PhD thesis to Harald as well.

**Comment by d97hah** [comment]
I've changed them accordingly for next version

2018-02-15 8:38 GMT+01:00 Hedvig Skirgård <notifications@github.com>:

**Comment by haspelmath** [comment]
Well, according to the principles laid out in my 2017 paper on language names, there are two problems:

- macrons are not well- formed in English names
- names should not be changed unless there is a compelling reason; the fact that speakers use a certain name is not compelling (we don't rename Swedish to Svensk)

So I think that this needs more justification.

Martin

Von meinem iPad gesendet

**Comment by HedvigS** [comment]
Swedish people do not generally object to being called "Swedish" in English. Penrhyn is the name of a ship that happened to find an island, it seems unnecessary to carry that convention forward. Rarotongan is the name of a dialect of a language spoken on more islands than just Rarotonga. 

There are (unfortunately) few people who write and care about these languages. Many/most or maybe even all of them agree with Akevai. Glottolog is a reference source that people who don't know much about these languages turn to, it would be good to spread information that people who speak and work on these languages support. 

This would be my further justification. Thank you for your time.

**Comment by haspelmath** [comment]
My question is: Do speakers of Penrhyn object to the name Penrhyn? Has any other name been used prominently by others?

If not, I don‘t think Glottolog should adopt another name. 

Incidentally, Wikipedia also mentions Tongarevan, which would be far more transparent. 

In general, I fear that linguists are often overzealous in indigenizing names. In North America (and maybe Australia), the speakers often share these sentiments, but elsewhere this is much rarer. Sweden is everywhere...

Von meinem iPhone gesendet
