### ISSUE TITLE
Some new coordinates for Kam [kdx] (and Dirim [dir])

### ISSUE THREAD

**Issue by jlesg** [clld/glottolog#205]
I don't know if this is the right place to post this, but here's some coordinates I collected in the field for Kam. (Where did the current coordinates come from? Just out of interest; maybe there are Kam groups I haven't been in touch with)

Kam [kdx]:
- 8°18'18.00"N, 11° 3'22.00"E - Village Sarkin Dawa - this is where the political representative of the Kam lives today, and approximately where he has lived since the beginning of the British administration
- 8°20'14.75"N, 11° 7'48.64"E - Village Kamaajim 1 - this is one of the places where they lived traditionally (in and around the Kamaajim mountain), and supposedly close to where the traditional chief has lived for centuries, which may be an even better location, but I could not visit that place for cultural reasons.

I would suggest the Sarkin Dawa coordinates, as Sarkin Dawa lies at the center of the whole contemporary Kam speaking area, Kamaajim 1 may be more representative of the traditional area, but I'm not entirely sure of that.

I also have some for Dirim, but as I don't know the extent of the area where Dirim is spoken, they may not be representative for the whole language. Meek (1931: 398) says the Dirim and Taram are "not localized" because of exogamy. The Dirim I have coordinates for may just be one group that is closely tied to the Kam. I'm curious where the previous coordinates come from?

Dirim [dir]:
- 8°26'22.20"N, 11° 6'40.00"E: the township of Garba Chede, where the political representative of the Dirim lives (at least the representative in this area)
- 8°21'41.00"N, 11° 2'59.00"E: the village of Kankani, where the traditonal chieftain of the Dirim lives according to the Kam chief

I don't know which village is a better representation of where most speakers of Dirim live in this area.

All the best,

Jakob

**Comment by xrotwang** [comment]
@jlesg it is the right place! If you feel a bit more adventurous, you could
- fork the repository
- edit the coordinates as you see fit, e.g. [here](https://github.com/clld/glottolog/blob/7d141f51a338cee8fc14fc873915d88c976d0cdf/languoids/tree/atla1278/volt1241/nort3149/kamm1249/md.ini#L7-L8)
- submit [a pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

**Comment by jlesg** [comment]
Done for Kam, thanks for the suggestion! Is there any information on where coordinates generally come from or on the reliability of coordinates (couldn't find any information on that anywhere so far)?

**Comment by xrotwang** [comment]
Some info is here: https://github.com/clld/glottolog/blob/master/SOURCES.md#language-location

When you say "done", something must have gone wrong, because I don't see the pull request showing up here: https://github.com/clld/glottolog/pulls

**Comment by jlesg** [comment]
Thank you! Attempt 2... This issue can be closed if you want.
