### ISSUE TITLE
computer assignment error

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog#210]
The automatic assignment has stuffed up a little for "North Tanna" by using Naka. The following refs are not correctly assigned:

Montaño Hernández, Alváis. no date. Ti naka tu gichi ka rllnee quieruu[;] Éste es un papel que habla de nosotros. Unidad Regional Oaxaca, Dirección General de Culturas Populares, Secretaría de Educación Pública, México. 44pp.

Harada Masaharu. 1957. Spoken Burmese to sono naka no joshi [Spoken Burmese and its particles]. Osaka Gaigokugo Daikaku Gakuhō 7. 216-43.

Harada, Masaharu. 1957. Spoken Burmese to sono naka no joshe [Spoken Burmese and its particles]. Osaka Gaigokugo Daikaku Gakuho (Journal of the Osaka University of Foreign studies) 7. 216-43.

**Comment by d97hah** [comment]
Thanks fixed for next version

2018-04-04 9:28 GMT+02:00 Hedvig Skirgård <notifications@github.com>:
