### ISSUE TITLE
Name change: Ngkâlmpw Kanum -> Ngkontar Ngkolmpu

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog#213]
Language ngka1235 is known as "Ngkâlmpw Kanum" in Glottolog now, after Donohue. The recent PhD thesis on the language uses the name "Ngkolmpu". Matt writes the following regarding the languages intelligibility and naming:

Page: 2-3
_Ngkolmpu refers both to the name of the people and by extension the name of the language they speak, i.e. the Ngkolmpu Language. There are two varieties of Ngkolmpu, Ngkontar and Baedi, which correspond to the two villages Yanggandur and Onggaya. The majority of speakers live in these two villages and the entire population live within Wasur National Park, a national park in the area east of Merauke. The variety described in this thesis is Ngkontar Ngkolmpu which is spoken by around 150 adults in the village of Yanggandur. All data was collected from speakers living in Yanggandur._

_The other variety, Baedi, is reportedly only spoken by a handful of elderly speakers
who no longer use it as a language of communication._

_The full name of the language is Ngkontar Ngkolmpu Kiki, the word kiki meaning ‘speak’, ‘talk’, ‘word’ or ‘language’. Ngkontar refers to the Ngkolmpu people living in Yanggandur and the variety of the language they speak. The language is also known by a number of other names. As this is a traditionally multilingual environment with a large number of closely related languages spoken over a relatively small area, people commonly need to make reference to the different languages of the area. In these in- stances, a shibboleth term is used consisting of the word meaning ‘this type’ optionally along with the word for ‘speak’ or ‘language’ in that language. Such terms are primar- ily used when one is comparing the languages, in which case Ngkontar Ngkolmpu is known as Ngkntra Kiki, [ŋkə̆ˈntra]. These terms are discussed in more detail in the following section._

_Much previously published work has referred to the language as ‘Kanum’. This was the term used in Boelaars (1950) and in the works published by Mark Donohue, discussed in Section 1.4. The variety described in these two sources is the same as that described in this thesis, although naturally due to the time the 􏰃ieldwork was con- ducted there are many differences between the three sources. Donohue also uses the name Ngkolmpu in his work along side the name Kanum, although in the orthography adopted in those papers Ngkolmpu is written as Ngkâlmpw. More details on the or- thography used in this thesis can be found in Section 2.6. Outside of these sources, the term ‘Kanum’ is used to refer to all the Tonda subgroup family speakers living within Indonesia. This term is used self-identifyingly in the form [kə̆ ˈnumɛ]. This same term, in the form of [ˈkanum], is the word typically given when non-Kanum people ask for the name of the people or the languages spoken in the villages in the region. The term has also been used by ethnographers, namely Nevermann (1939) and van Baal (1966), to refer to the people living in this area. Boelaars (1950) suggests the term comes from Marind referring to people living east of the Maro river although he provides no evi- dence to support the claim._

page 5:

_Ngkolmpu consists of two varieties, Ngkontar and Baedi. As stated, Baedi is no longer a spoken language and people report that it is only remembered by a handful of older people. In my time in the 􏰃ield I never visited Onggaya, however I met a number of people, mostly men in their 50s, who identi􏰃ied as Baedi people and who lived in Onggaya. All of these people stated they could not speak nor understand the language. It was also clear from observation that they could not speak or understand Ngkontar Ngkolmpu either._

Based on this I would suggest

Ngkâlmpw Kanum -> Ngkontar Ngkolmpu

and correspondingly for badi1247

Bädi Kanum -> Ngkontar Bädi  or Ngkontar Baedi

**Comment by d97hah** [comment]
I've adjusted the names accordingly

2018-04-12 5:27 GMT+02:00 Hedvig Skirgård <notifications@github.com>:
