### ISSUE TITLE
ukra1235 - wrong link to wikipedia

### ISSUE THREAD

**Issue by noellarh** [clld/glottolog#215]
On the page for Ukrainian Sign Language, ukra1235, the Wikipedia link goes to Russian Sign Language instead of the page for Ukrainian Sign Language - https://en.wikipedia.org/wiki/Ukrainian_Sign_Language

**Comment by xflr6** [comment]
Thanks. Actually glottolog links to the correct iso code (http://en.wikipedia.org/wiki/ISO_639:ukl) but the redirect page from the ISO-code on Wikipedia forwarded to the wrong page. Fixed: https://en.wikipedia.org/w/index.php?title=ISO_639:ukl&redirect=no
