### ISSUE TITLE
resource from Pitcairn-Norfolk not tagged correctly

### ISSUE THREAD

**Issue by unael** [clld/glottolog#220]
http://glottolog.org/resource/languoid/id/pitc1234 

"A Dictionary of Norfolk Word and Usages" is tagged as a dictionary, but it has 53 pages, not enough to be called a dictionary according to this page: http://glottolog.org/meta/glossary#doctype-dictionary

**Comment by d97hah** [comment]
Indeed, thx, will fix for next version.

2018-05-04 18:24 GMT+02:00 unael <notifications@github.com>:
