### ISSUE TITLE
Coding/escape character issue in koro1316

### ISSUE THREAD

**Issue by chrzyki** [clld/glottolog#235]
The \`` [here](https://github.com/clld/glottolog/blob/master/languoids/tree/sino1245/macr1268/koro1317/koro1316/md.ini) (and [here in Glottolog CLLD](http://glottolog.org/resource/languoid/id/koro1316)) kind of destroys the Markdown coding until the next \``. Could potentially be happening in other places as well?

**Comment by d97hah** [comment]
Fixed in that specific place, haven't checked other places

Pada tanggal Sen, 16 Jul 2018 pukul 16.50 Christoph Rzymski <
notifications@github.com> menulis:
