### ISSUE TITLE
Incompatible versions of tree and language files

### ISSUE THREAD

**Issue by oesten** [clld/glottolog#239]
I downloaded glottolog-3.3.zip from https://github.com/clld/glottolog/releases just a little while ago. There seems to be discrepancies between the language files in the languoids folder and the files in the languoids/tree folder. For instance, the record for Indonesian in "languages_i.md" reads

[Indonesian [indo1316][ind]](tree/aust1307/nucl1752/mala1545/mala1536/nort3170/mala1538/nucl1733/indo1326/indo1316/md.ini)

but there is no node "nucl1752" under "tree/aust1307". The correct path for Indonesian is

tree\aust1307\mala1545\mala1536\nort3170\mala1538\nucl1733\indo1326\indo1316

If you search for "nucl1752" on Google you are directed to an older version of Glottolog. The language files are one year old. 

- Östen Dahl
oesten@ling.su.se

**Comment by xrotwang** [comment]
Ah, right. I forgot to recreate the index files when releasing! Thanks for
noticing. I hope to release a bugfix 3.3.1 soon.

Östen Dahl <notifications@github.com> schrieb am Fr., 3. Aug. 2018, 13:27:

**Comment by oesten** [comment]
Thanks! Östen

**Comment by xrotwang** [comment]
@oesten Release 3.3.1 https://github.com/clld/glottolog/releases/tag/v3.3.1 should have consistent tree and index files.
