### ISSUE TITLE
english is listed as critically endangered?

### ISSUE THREAD

**Issue by nthieberger** [clld/glottolog#240]
https://github.com/clld/glottolog/blob/master/languoids/tree/indo1319/germ1287/nort3152/west2793/nort3175/angl1264/angl1265/merc1242/macr1271/stan1293/md.ini

**Comment by xrotwang** [comment]
Must have accidentally inherited the status of one of its dialects - would be my first guess. Thanks for spotting!

**Comment by xrotwang** [comment]
Looks like it, see below. @d97hah the languages listed in the comment don't exactly look like varieties of English, though.
```bash
$ git diff 8984ab2575b5df48b97ff1a7d8f9455a6bd8fdf1 22d7f3e5cd11262fa8ead067929e1fd1807b9160  languoids/tree/indo1319/germ1287/nort3152/west2793/nort3175/angl1264/angl1265/merc1242/macr1271/stan1293/md.ini
diff --git a/languoids/tree/indo1319/germ1287/nort3152/west2793/nort3175/angl1264/angl1265/merc1242/macr1271/stan1293/md.ini b/languoids/tree/indo1319/germ1287/nort3152/west2793/nort3175/angl1264/angl1265/merc1242/macr1271/stan1293/md.ini
index 608508f..3b6a3f6 100644
--- a/languoids/tree/indo1319/germ1287/nort3152/west2793/nort3175/angl1264/angl1265/merc1242/macr1271/stan1293/md.ini
+++ b/languoids/tree/indo1319/germ1287/nort3152/west2793/nort3175/angl1264/angl1265/merc1242/macr1271/stan1293/md.ini
@@ -35,6 +35,8 @@ countries =
        United Kingdom (GB)
        United States (US)
        Venezuela, Bolivarian Republic of (VE)
+agglomerated_endangerment = 8b (Nearly extinct)
+agglomerated_endangerment_source = UNESCO [Sat Aug 19 22:02:46 2017] Bay Islands Creole (2087-) = Critically endangered; Yola (1601-) = Extinct; Bungee (2396-) = Critically endangered
 

```

**Comment by d97hah** [comment]
Thanks both, yes this happened because dialects of English (they are
dialects of English) are listed as critically endangered in UNESCO whereas
English itself is not listed. I was aware of this possibility (also happens
for French) and thought I had fixed it but apparently not. I fixed English
and French and will look for others

Pada tanggal Sen, 6 Agt 2018 pukul 13.00 Robert Forkel <
notifications@github.com> menulis:

**Comment by nthieberger** [comment]
terima kasih
