### ISSUE TITLE
update reference by Blench on Bantoid

### ISSUE THREAD

**Issue by igoryanovich** [clld/glottolog#241]
Hi everyone, 

You probably want to supplement the reference Blench 2009 on Bantoid with Blench 2015 "The Bantoid languages", Oxford Handbooks Online, Linguistics, OUP, doi:10.1093/oxfordhb/9780199935345.013.17. 

The trees appear to be similar between the two texts, and generally 2015 is clearly a descendant of 2009, but the two contain a considerable amount of non-overlapping material.

**Comment by d97hah** [comment]
What is the non-overlapping material such that the 2015 supersedes the 2009?

Pada tanggal Sen, 6 Agt 2018 pukul 02.03 igoryanovich <
notifications@github.com> menulis:

**Comment by igoryanovich** [comment]
For example, the 2009 (or rather the ms. that I happen to have, which is
explicitly marked as not for citing) does not have a summary table on ATR
harmony in Bantoid, etc. etc.

More generally, the 2015 paper is a published work, unlike the 2009 one.

**Comment by d97hah** [comment]
But I mean for classification (as the refs are for there for
classification). The 2015 may be published but does not have the richer
information on justification for that clf that the 2009 has.

Pada tanggal Sen, 6 Agt 2018 pukul 17.18 igoryanovich <
notifications@github.com> menulis:

> For example, the 2009 (or rather the ms. that I happen to have, which is
> explicitly marked as not for citing) does not have a summary table on ATR
> harmony in Bantoid, etc. etc.
>
> More generally, the 2015 paper is a published work, unlike the 2009 one.
>

**Comment by igoryanovich** [comment]
I have not looked very carefully, but the general structure of the
classification seems to be at least very similar.
It just seems like a more stable, and also more authoritative, reference to
use.
