### ISSUE TITLE
Tangkhulic separation

### ISSUE THREAD

**Issue by gldrk** [clld/glottolog#246]
Tangkhulic [sino1246] looks like it fell out of Sino-Tibetan accidentally, or is ‘Sino-Tibetan, Kuki-Chin-Naga, Naga, Tangkhul-Maring, Tangkhulic’ just a weird name for a new family?

**Comment by d97hah** [comment]
That's an error, it should be in S-T at that place. I've just put in a PR
with a fix. Thanks for spotting that! H

Pada tanggal Jum, 17 Agt 2018 pukul 04.12 gldrk <notifications@github.com>
menulis:
