### ISSUE TITLE
Notes alongside languoid folders do not correspond to that languoid. 

### ISSUE THREAD

**Issue by PaulHeggarty** [clld/glottolog#248]
While exploring the file structure for Germanic languages, for example at ...
https://github.com/clld/glottolog/tree/master/languoids/tree/indo1319/germ1287
...  I notice that the notes that appear alongside the languoid folders do not have anything to do with those languoids.  The note alongside East Germanic east2805 is about the Great Andamanese language in the Indian Ocean, for example, and the one alongside North+West Germanic  nort3152 is about Northern Paman languages, in Australia.

![screenshot - 2018 08 18 21_37_14](https://user-images.githubusercontent.com/8819910/44302723-15d6f700-a32f-11e8-9606-a09e48229f96.png)

**Comment by xflr6** [comment]
If you click on the commit message, you can see that the respective commit did actually include changes to the germ1287 directory.

**Comment by PaulHeggarty** [comment]
OK, thanks for the clarification!
