### ISSUE TITLE
Newick serialisation of isolates with dialects is incorrect

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog#261]
Note duplicated dialect nodes below:
```bash
$ glottolog newick | grep pawa1255
(('Aurama [aura1242]':1,'Hauruha [haur1243]':1)'Pawaia [pawa1255][pwa]-l-':1)('Aurama [aura1242]':1,'Hauruha [haur1243]':1)'Pawaia [pawa1255][pwa]-l-':1;
```

**Comment by xrotwang** [comment]
@SimonGreenhill should be ok now (note that the node `pawa1255`) still gets duplicated, because isolates are wrapped in a pseudo family:
```bash
$ glottolog newick | grep pawa1255
(('Aurama [aura1242]':1,'Hauruha [haur1243]':1)'Pawaia [pawa1255][pwa]-l-':1)'Pawaia [pawa1255]':1;
```

**Comment by SimonGreenhill** [comment]
Thanks -- looks good. The labels of `'Pawaia [pawa1255][pwa]-l-'` and `'Pawaia [pawa1255]'` are different, so that should be ok (I'll check, but if it becomes a problem then the latter could be something like `'Pawaia [pawa1255]-f-` or something).

**Comment by xrotwang** [comment]
Yes. I considered the old (copied) labels a bug - because the top-level wrapper shouldn't have the `-l-` flag. Instead, I now create a "proper" wrapper family and pass it to the label template.

**Comment by SimonGreenhill** [comment]
Great, no other obvious clashes happening now thanks!
