### ISSUE TITLE
lihi1237 incorrect sources

### ISSUE THREAD

**Issue by rhiannon-schembri** [clld/glottolog#269]
All the sources listed for Lihir (lihi1237) except the following are not for Lihir

Malcolm Ross. 1988. Proto-Oceanic and the Austronesian languages of western Melanesia. (Pacific Linguistics: Series C, 98.) Canberra: Research School of Pacific and Asian Studies, Australian National University. xiii+487pp. (Publication of PhD, ANU 1987.)

Stephan, Emil and Graebner, Fritz. 1907. Neu-Mecklenburg (Bismarck-Archipel)- Die Küste Von Umuddu Bis Kap St. Georg- Forschungsergebnisse Bei den Vermessungsfahrten Von S.M.S. Möwe im Jahre 1904. Berlin: Dietrich Reimer (Ernst Vohsen). 296pp.

Neuhaus, Karl. 2015 [1954]. Grammar of the Lihir Language of New Ireland, Papua New Guinea. Boroko: Institute of Papua New Guinea Studies. 284pp.

Neuhaus, Karl. 1954. Grammatik der Lir-Sprache in Melanesien. (Micro-Bibliotheca Anthropos, 20.) Posieux: Anthropos Institut. i+219pp. (Microfilm).

Min-ha Park and Shin-Hee Park. 2003. Lihir organised phonology data. unpublished. 6pp.

**Comment by rhiannon-schembri** [comment]
Also, these ones are correct:
Rudolf Pöch. 1908. Wanderungen im nördlichen Teile von Süd-Neumecklenburg. Globus 93. 7-13.
Albert Hahl. 1907. Das Mittlere Neumecklenburg. Globus 91. 310-316.

Basically there are just a lot of sources that need checking. Sorry for any confusion

**Comment by d97hah** [comment]
Thanks Rhiannon! It was because of the erroneous trigger word "teile", now
fixed for next version. all the best, H

Pada tanggal Sen, 5 Nov 2018 pukul 07.11 Rhiannon Schembri <
notifications@github.com> menulis:
