### ISSUE TITLE
Reference language assignment error 

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog#285]
This reference:

* Stanford, Jim. n.d. When your mother tongue is not your mother's tongue: Linguistic reflexes of Sui exogamy. University of Pennsylvania Working Papers in Linguistics: Selected Papers from NWAV-34 12. 217–229.

has been assigned to [waim1255] when it should be assigned to [suii1243]. The warning note says that this is due to "computerized assignment from "exogamy")". It may be worth checking through other references that have been assigned because of "exogamy".

This reference
* Stanford, James N. 2009. 20. Clan as a sociolinguistic variable: Three approaches to Sui clans. In Stanford, James N. and Preston, Dennis R. (eds.), Variation in Indigenous Minority Languages, 463-484. Amsterdam/Philadelphia: John Benjamins Publishing Company.

should also be assigned to [suii1243]

I know this happens sometimes and I'm grateful that you guys update when it's noticed.

**Comment by d97hah** [comment]
Thanks I've fixed it for next version

Pada tanggal Sen, 10 Des 2018 pukul 05.27 Hedvig Skirgård <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
See https://github.com/clld/glottolog/commit/6913145dbc69b881e9d121072f4ea6cc1de7f19a
