### ISSUE TITLE
Duplicate dialects "Oost-Vlaams" and "Oostvlaams"

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog#287]
Currently there's a dialect [Oost-Vlaams](https://glottolog.org/resource/languoid/id/oost1241) under Dutch, and one [Oostvlaams](https://glottolog.org/resource/languoid/id/oost1242) under Vlaams. Are these duplicates?

**Comment by d97hah** [comment]
Thanks I'll fix that for next version

Pada tanggal Kam, 13 Des 2018 pukul 16.25 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
@d97hah what about addressing things like this in mini, but targeted commits/pull requests?

**Comment by d97hah** [comment]
Usually b/c overhead doing a PR for a tiny change is too large, this time
b/c of intermittent internet access on travels

Pada tanggal Jum, 14 Des 2018 pukul 09.58 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
I see your point. In case there are particular open issues, it would be nice if we had the connection between PR and issue "in the system". This can also be done by adding "closes #NUMBER" in the PR description.
