### ISSUE TITLE
North-Central Atlantic

### ISSUE THREAD

**Issue by gldrk** [clld/glottolog#289]
See now J. Merrill’s PhD thesis (2018) ‘The historical origin of consonant mutation in the Atlantic languages’ for a negative evaluation of the various Atlantic proposals, with critique of Pozdniakov & Segerer (2017).

**Comment by d97hah** [comment]
I only had a chance to read through it last week and I agree with he
criticism so I've made an update for next version which includes i)
dropping the N Atlantic node, ii) dropping the Tenda-Jaad node, iii) adding
a Wolof-BKK node. Guillaume told me Konstantin is or has written a detailed
reply but until that shows up I think the reasoning in Merrill's thesis is
current. all the best, H

Pada tanggal Rab, 26 Des 2018 pukul 02.26 gldrk <notifications@github.com>
menulis:

**Comment by xrotwang** [comment]
see https://github.com/clld/glottolog/commit/4d3c0b2efb1061945d5b937142e69f1c913de083
