### ISSUE TITLE
Arop-Sissano incorrect sources

### ISSUE THREAD

**Issue by rhiannon-schembri** [clld/glottolog#290]
Many of the sources listed for Arop-Sissano (arop1242) seem to be incorrect - mostly German ones, the listing appears to be triggered by the word "unserer" which is selecting some papers about German and other German colonies in Africa

**Comment by xrotwang** [comment]
see https://github.com/clld/glottolog/commit/1caf32a7904b3278b3240310cb964f4e68ef518f
