### ISSUE TITLE
long/lat adjustments in Oceania

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog#294]
Peering over maps based of glottolog, I've noticed a few things that may need to be adjusted. These strike me as improved locations.

Tutuba -> -15.580667, 167.268889
Orkon-Fanbak -> 16.210501, 168.212109

I'm not sure what the best point is for Vaeakau-Taumako, but I think it's worth asking Åshild and/or Alex because right now it's in a bit of a funny place. I can ask them if you want.

**Comment by d97hah** [comment]
Thanks Hedvig! I'll update them accordingly.

Pada tanggal Sen, 14 Jan 2019 pukul 14.15 Hedvig Skirgård <
notifications@github.com> menulis:

**Comment by HedvigS** [comment]
Oh, just noticed that I had missed a minus when copy-pasting.

Orkon-Fanbak -> **-** 16.210501, 168.212109
