### ISSUE TITLE
Bibliography for Nafusi (nafu1238)

### ISSUE THREAD

**Issue by IanMaddieson** [clld/glottolog#295]
In the bibliography for Nafusi (nafu1238) the following is definitely out of place. This work relates to Paraguayan Guarani and has nothing to do with the Berber language Nafisi. (I note the reference is flagged with a warning.):  
Durán Estragó, Margarita. 2000. La misión del Pilcomayo: 1925-2000. Memoria viva. Biblioteca Paraguaya de Antropolgía 35.

Note also that the following reference has nothing to do with Nafisi but concerns language choice in education in Namibia:
Harlech-Jones, Brian. 1998. Viva English! Or, is it time to review language in education?. Reform forum: journal for education reform in Namibia 6. 9-15.

The third flagged entry in the bibliography for Nafusi is indeed about this language, namely:
Beguinot, Francesco. 1924. A proposito di una voce libica citata da Erodoto. Africa italiana: bolletino della Società Africana d'Italiana 3 [43].

**Comment by IanMaddieson** [comment]
Sorry that idiotic autocorrect over-ruled my several times correcting the spelling of NAFUSI

**Comment by d97hah** [comment]
Thanks Ian, I've fixed that for next version!

Pada tanggal Kam, 17 Jan 2019 pukul 05.48 IanMaddieson <
notifications@github.com> menulis:
