### ISSUE TITLE
Language family refs not shown for isolates

### ISSUE THREAD

**Issue by d97hah** [clld/glottolog#298]
E.g. for 
https://glottolog.org/resource/languoid/id/gaga1251

The references for the family status (in gaga1251/md.ini) are not shown 

[classification]
family = Evidence for an Arnhem family or a Gunwinyguan affiliation is not sufficient.
familyrefs = 
	**hh:hv:Evans:Non-Pama-Nyungan**
**hh:hv:Evans:Australia**

**Comment by xrotwang** [comment]
Moved to https://github.com/clld/glottolog3/issues/107
