### ISSUE TITLE
Computer-assigned reference error

### ISSUE THREAD

**Issue by joeylovestrand** [clld/glottolog#299]
Merlan, Francesca and Rumsey, Alan. 1986. A marriage dispute in the Nebilyer Valley (Western Highlands Province, Papua New Guinea). In Linda K. Jones... (ed.) Canberra. 69-180pp.

was erroneously computer-assigned to waru1266

**Comment by d97hah** [comment]
Thanks JOey! Fixed that for next version.

Pada tanggal Sel, 29 Jan 2019 pukul 09.01 joeylovestrand <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
see https://github.com/clld/glottolog/commit/3973ab41c6ae3f81a85924d6dd3674dd863194f1
