### ISSUE TITLE
Suggested relocation of 2 languoid points in East Africa

### ISSUE THREAD

**Issue by kirbykat** [clld/glottolog#303]
Hi, I believe two languoids in East Africa should have their lat/long coordinates adjusted. In each case the move is supported by at least two other datasets/sources:

Shambaa - sham1280, ksb
Current Glottolog lat, long: -6.3000, 39.35000
Suggested lat, long: -4.70219, 38.31230 (Source: Ethnologue/GMI); 
Supported by: Ethnographic Atlas coordinates for this group (-5.000000, 38.000000); Pers. Comm. Bronwen Powell, Penn State U Geography/African Studies (BP has worked with this language group).

Sangu - sang1330, sbp, 
Current Glottolog lat, long: -6.300000, 39.350000
Suggested lat, long: -8.40340, 34.07405 (Source: Ethnologue/GMI). 
Supported by D-PLACE (Ethnographic Atlas) coordinates for this group: -8.0000, 34.0000.

**Comment by xrotwang** [comment]
ok. will update

**Comment by kirbykat** [comment]
@d97hah @xrotwang, great. thanks. Is there a way I can get the most-up-to-date version of the lat longs - I am about to re-run some mapping I first did over a year ago, and would love to have the latest version to work with. Is that what is here: https://glottolog.org/meta/downloads, under v. 3.3? (If yes, I just downloaded it, so that is good). Thanks, Kate

**Comment by xrotwang** [comment]
@kirbykat No, v3.3 is the latest **released** version of Glottolog. The current work-in-progress is available in this repository - but would need to be accessed using the python API.
