### ISSUE TITLE
Incorrect source listed for Label (labe1239)

### ISSUE THREAD

**Issue by rhiannon-schembri** [clld/glottolog#305]
Saalbach & Imai 2006 is listed as a source for Label (labe1239) but appears to be an CLA or psycholinguistic study for German and Chinese. The trigger word for the listing is "label" - the name of the Label language but in this context it is "label extension"

**Comment by d97hah** [comment]
Thanks fixed for next version

Pada tanggal Rab, 6 Feb 2019 pukul 12.47 Rhiannon Schembri <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
@d97hah when you say "fixed for next version", wouldn't this mean the change must be already pushed to master with any of the last PRs? So far, [`label` is still listed under `[triggers]`](https://github.com/clld/glottolog/blob/dff21a77e40064fbdcd8585b6334ac6f75c853c9/languoids/tree/aust1307/mala1545/cent2237/east2712/ocea1241/west2818/meso1253/newi1242/stge1234/labe1241/labe1239/md.ini#L23-L25).

**Comment by d97hah** [comment]
"Label" should still be there, I added lgcode:s to the offending refs
instead, preventing them from being autotagged. all the best, H

Pada tanggal Jum, 22 Feb 2019 pukul 10.38 Robert Forkel <
notifications@github.com> menulis:
