### ISSUE TITLE
Add codes for Bena (bena1262) dialects

### ISSUE THREAD

**Issue by tresoldi** [clld/glottolog#310]
For full lexibank integration of the data by Mitterhofer (2013) ("Lessons from a Dialect Survey of Bena: Analysing Wordlists"), we need codes for the dialects of Bena (Tanzania) `bena1262` listed in the work.

The dialects compose two or three major groups, depending on how one decided to divide them, but as we have no third-party confirmation they should probably all be listed one node below `bena1262`. The dialects are referred to by the native name of the villages where they are spoken, which were difficult to find because they are not in any major gazetteer or information is clearly wrong. I used the map in p. 30 of the reference to look for the human settlements of the provided size using satellite images; I am confident the coordinates below are within ~ 30 seconds of latitude and longitude in all cases.

  | Name | Latitude | Longitude |
  |--------|-----------|------------|
  | Ihanja | -9.10589 | 34.6563 |
  | Ikuna | -9.13708 | 34.9083 |
  | Itambo | -9.36073 | 35.32647 |
  | Itipula | -9.34988 | 35.21523 |
  | Kanamalenga | -8.91872 | 34.63776 |
  | Liwengi | -9.58491 | 35.12116 |
  | Lwanzali | -9.3404 | 35.27635 |
  | Makanjaula | -9.52396 | 34.79638 |
  | Ujindile | -9.24553 | 34.50936 |
  | Ukalawa | -9.18589 | 35.28047 |
  | Utalingoro | -9.4366 | 34.70918 |
  | Utengule | -8.94924 | 34.76754 |
  | Wangama | -9.17368 | 34.497 |

**Comment by d97hah** [comment]
Ok I've added them:

https://github.com/clld/glottolog/pull/315

Pada tanggal Kam, 21 Feb 2019 pukul 09.03 Tiago Tresoldi <
notifications@github.com> menulis:

**Comment by tresoldi** [comment]
Thank you, @d97hah !
