### ISSUE TITLE
lang tags for names

### ISSUE THREAD

**Issue by eroux** [clld/glottolog#312]
looking at [this diff](https://github.com/clld/glottolog/pull/311/files#diff-25854a7f97c1565a425389c63e3f51ba), it's quite obvious that `Ü` and `Dbus` are in fact the same name: `Dbus` is a transliteration of `དབུས`,  pronounced /y/, a pronunciation often rendered as `ü`.

I'm wondering if it would be possible to indicate the lang tag for the name? In this case there could be
```
"Ü"@en
"དབུས"@bo-Tibt
```

I'm sure I'm not the first one to think about this, but I thought I'd just ask, in order to understand what the policy is.

**Comment by d97hah** [comment]
Yes they are like you say and hence Ü is the name for what was previously
called Dbus (and reflected in the glottocode, though this is not
significant). Robert is probably in a better position to answer about a
language tag for the name.

Pada tanggal Kam, 21 Feb 2019 pukul 16.55 Elie Roux <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
The general policy for the primary names in Glottolog is that these are English names. Alternative names are not collected very systematically - they are added, if we think it will improve navigation, i.e. make languages easier to find. So if we collect too many alternative names - with too many name clashes across languages - the purpose of enhancing navigation won't be met.

Regarding alternative names in other languages: So far we've only included some from lexvo, and these do have language tags, see https://github.com/clld/glottolog/blob/f67c89d2026f8df8ec9d8133c10c5b26e96132b4/languoids/tree/indo1319/germ1287/nort3152/west2793/fran1268/high1287/stan1295/md.ini#L69-L75

**Comment by eroux** [comment]
Oh I see, so there is a way to indicate the lang tag, that's really good. I don't think adding the name in Tibetan script can clash with search in other languages, and it would help the search by Tibetan people (who are far more familiar with the Tibetan script than the transliteration or Romanization). I can make a pull request to add the Tibetan name, would that be ok?

**Comment by xrotwang** [comment]
Yes, that's ok. Add it in a `glottolog = ` option under the  `altnames` section. Thanks!

**Comment by eroux** [comment]
done: https://github.com/clld/glottolog/pull/314

**Comment by eroux** [comment]
thanks, no need to keep this issue open
