### ISSUE TITLE
Long lat for some languages in the NG region

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog#317]
As I'm prepping for the finalization of the pacific maps I'm having made, I took the liberty of assigning some long/lats to languoids that had missing coordinates in Glottolog. They're not all ideal, but at least they're roughly in the right area. I'll be using them, because I'd rather have them in the right area and a little bit off than entirely excluded. I went by clues in Glottolog documents for the languages and wikipedia notes.

mara1417 
-10.825887, 162.190100

hora1238
3.005176, 131.172218

enga1253
-5.408371, 143.441436

ambe1246
-1.763355, 137.903651

mari1446
-16.593829, -148.426730

mehe1245
-3.674688, 142.606174

sina1273
-5.954719, 145.025508

**Comment by haspelmath** [comment]
Thanks for this!

**Comment by d97hah** [comment]
Thanks a lot Hedvig, I've included their additions for the next Glottolog
update.

Pada tanggal Rab, 13 Mar 2019 pukul 08.35 Martin Haspelmath <
notifications@github.com> menulis:

**Comment by HedvigS** [comment]
Här kommer mera:

Language_name | Glottocode | Latitude | Longitude
-- | -- | -- | --
Maritime Polynesian Pidgin | mari1446 | -148.42673 | -16.593829
Duvle-Wano-Pidgin | duvl1238 | 138.200358 | -3.013068
Arafundi-Enga Pidgin | araf1245 | 143.298006 | -5.101836
Hauna Trade Language | haun1238 | 141.625658 | -4.292336
Trading Eleman | hiri1235 | 146.23458 | -8.316580,
Trading Koriki | hiri1236 | 144.912033 | -7.775138
Imunga Trade Language | imun1234 | 146.565049 | -8.075280,
Ioi Trade Jargon | ioit1234 | 146.586897 | -8.103849
Kwoma-Manambu Pidgin | kwom1264 | 142.842763 | -4.072276
Tolai-Nakanai-Trade | tola1236 | 151.323615 | -4.903211
Yimas-Alamblak-Pidgin | yima1235 | 143.700473 | -4.94491
Yimas-Arafundi-Pidgin | yima1244 | 143.673827 | -4.883724
Yimas-Karawari Pidgin | yima1245 | 143.562895 | -4.639499
Yimas-Iatmul Pidgin | yima1246 | 143.419463 | -4.295923,

These locations are mainly estimated from:

Tom Dutton. 1983. Birds of a Feather: A pair of rare pidgins from the Gulf of Papua and Williams, Jeffrey P. 1993. Documenting the Papuan-Based pidgins of insular New Guinea. 

Seeing as Dutton seems to suggest that Trading Eleman and Trading Koriki are variants of Hiri Motu, they could either be made to be dialects of Hiri Motu or sister languages with Hiri Motu as a parent. I didn't have time to dig into this much more.

**Comment by HedvigS** [comment]
Oh, and 

Rennellese Sign Language  renn1236, 160.1761, -11.620933


160.1761 | -11.620933
-- | --




160.1761 | -11.620933
-- | --




160.1761 | -11.620933
-- | --

**Comment by HedvigS** [comment]
Calle B may be sending over heaps of sign language coordinates soonish too, just a heads up.

**Comment by HedvigS** [comment]
And I've asked Australianists to help out with 28 Australian languages with missing coordinates, mainly because they're extinct, pidgins or sign languages. We'll see how that turns out.

**Comment by xrotwang** [comment]
If you give pull requests a go, git would track your contribution, so
acknowledging it would be automates.

Hedvig Skirgård <notifications@github.com> schrieb am Do., 14. März 2019,
07:28:

**Comment by HedvigS** [comment]
@xrotwang yes I know but when I try I get an error message saying I don't have that permission

**Comment by HedvigS** [comment]
Found one more
Avok avok1244 -16.536653, 167.773866

**Comment by xrotwang** [comment]
@HedvigS you'd need to create the pull request from your **fork** of the repository, i.e. first hit the "fork" button on top right of the page, and then work from `HedvigS/glottolog`.

**Comment by HedvigS** [comment]
@xrotwang okay I'll give it another go.

**Comment by d97hah** [comment]
Thanks I've added them all. The Hiri Motu-based pidgins are already part of
the family "Motu based pidgin"

Pada tanggal Kam, 14 Mar 2019 pukul 07.21 Hedvig Skirgård <
notifications@github.com> menulis:

**Comment by d97hah** [comment]
Thx added!

Pada tanggal Kam, 14 Mar 2019 pukul 08.05 Hedvig Skirgård <
notifications@github.com> menulis:

**Comment by HedvigS** [comment]
I've assigned coordinates for 20 more Papunesia languages and 28 Australian that previously had missing. I'll prep my documents for the cartographer, but then I can either edit the md.ini files and make a pull request for all in batch, of copy-paste in a table here. Whichever Harald @d97hah  finds easiest to review.

**Comment by d97hah** [comment]
PR is easier to review

Pada tanggal Sel, 19 Mar 2019 pukul 04.30 Hedvig Skirgård <
notifications@github.com> menulis:

**Comment by HedvigS** [comment]
Check

**Comment by xrotwang** [comment]
looking forward to PR
