### ISSUE TITLE
Binahari dialect/language duplication

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog#322]
The Ma and Neme varities of Binahari can either be seen as two different languages (Dutton 1999) or two different dialects. Glottolog currently seems to do both, as far as I can tell.

There are the language-level languoids Binhari-Ma (bina1274) and Binahari (bina1275). There is also "Ma" (maaa1254)  as a dialect of Binahari (bina1275) and the dialect Neme (neme1245).

Please do one or the other, i.e. either remove bina1274 or remove maaa1254 and neme1245. Or tell me how this is meant to work.

Dutton (1999:93)
_it has been suggested that one of them. Binahari, is probably better regarded as consisting of two languages [Binahari-Ma and Binahari-Neme] rather than the two dialects described in the survey_

**Comment by HedvigS** [comment]
I'll wait with pushing any coordinates until this is resolved. The coordinates for the Ma dialect or language according to Dutton should be roughly -10.133855, 148.723092

**Comment by d97hah** [comment]
It's two diff lgs. The dialects are erroneous (the change was made before I
started caring about the dialect quality in Glottolog)

Pada tanggal Sel, 19 Mar 2019 pukul 03.16 Hedvig Skirgård <
notifications@github.com> menulis:

**Comment by HedvigS** [comment]
Cool cool, we're in agreement then :)! Tack

**Comment by HedvigS** [comment]
In that case bina1275 might be better labeled with the name "Binahari-Neme".

**Comment by d97hah** [comment]
Yes changed that too

Pada tanggal Sel, 19 Mar 2019 pukul 03.50 Hedvig Skirgård <
notifications@github.com> menulis:
