### ISSUE TITLE
Incorrect source listed for Tangga (tang1348)

### ISSUE THREAD

**Issue by rhiannon-schembri** [clld/glottolog#328]
The source 'Bahasa: Pembantu: Dari Rumah Tangga sampai Presiden' (Purwo 2007) listed for Tangga (tang1348) is actually for Bahasa

**Comment by d97hah** [comment]
Thanks I've fixed that for next version! H

Pada tanggal Sab, 23 Mar 2019 pukul 05.04 Rhiannon Schembri <
notifications@github.com> menulis:
