### ISSUE TITLE
Space in source page number placement

### ISSUE THREAD

**Issue by d97hah** [clld/glottolog#332]
The colon after a subclf/clf source is placed with a space before it, that is

https://glottolog.org/resource/languoid/id/cors1241
Agard, Frederick B. 1984 :61-73

Ideally, and according to unified style sheet for linguistics, this space should be after the colon, i.e.

Agard, Frederick B. 1984: 61-73

**Comment by xrotwang** [comment]
Moved to https://github.com/clld/glottolog3/issues/108
