### ISSUE TITLE
Misleading names of Qiang [qian1264] groupings

### ISSUE THREAD

**Issue by oesten** [clld/glottolog#336]
The subgroupings of the Qiang [qiang1264] are based on Sims 2016. For several of the groupings, especially the high-level ones, Sims uses shared innovations as labels rather than traditional names such as "Northern Qiang". For instance, one of the top-level branches in the tree in Sims' Figure 1 is labeled "upstream *_nu_-". This means that all the varieties in this branch have a directional prefix derived from Proto-Qiang *_nu_ meaning 'upstream'. In Glottolog, this branch is called "Upsteam Qiang". Disregarding the obvious misspelling, such a label is misleading in that it suggests that the varieties in question are located 'upstream' some river. The same goes for a number of other branches.

**Comment by d97hah** [comment]
Thanks I've fixed the upstream name. Re the other branches whose names you
say are misleading I can only spot

    Downward Southern Qiang [down1240]
    Inward Southern Qiang [inwa1234]

Are there more?


Pada tanggal Min, 31 Mar 2019 pukul 13.51 Östen Dahl <
notifications@github.com> menulis:

**Comment by oesten** [comment]
Thanks! No, these were the ones. "A number of" was literally true but maybe misleading. Sims has more but they don't show up in Glottolog.
