### ISSUE TITLE
Re-classify Izi-Ezaa-Ikwo-Mgbo

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog#38]
[Izi-Ezaa-Ikwo-Mgbo](http://glottolog.org/resource/languoid/id/izie1238) is currently classified as a language with 4 dialects
```
$ glottolog tree izie1238
Izi-Ezaa-Ikwo-Mgbo [izie1238] <l>
   ├─ Ezaa [ezaa1238] <d>
   ├─ Ikwo [ikwo1238] <d>
   ├─ Izi [izii1239] <d>
   └─ Mgbo [mgbo1238] <d>
```
although ISO has split [izi](http://www-01.sil.org/iso639-3/documentation.asp?id=izi) into 4 distinct languages, and the name in Glottolog looks as if we consider it as a subfamily as well.

In any case, I think, we should assign the new ISO codes to what is now dialects in Glottolog. But we may also want to turn these into languages and Izi-Ezaa-Ikwo-Mgbo into a family.

**Comment by d97hah** [comment]
The information in the split request is squarely at odds with Meier
(1975:15-16) who says they are 95% lexicostatistically similar which would
make it pretty impossible for them to be unintelligible (like the iso-split
request says). Meier (1975:15-16) is better argued. There's nothing
hindering the assignment of the (in my view erroneous) iso-codes to the
subvarieties though.

2016-12-09 9:08 GMT+01:00 Robert Forkel <notifications@github.com>:

**Comment by xrotwang** [comment]
Ok. will do and make pull request.

**Comment by xrotwang** [comment]
Should Meier (1975:15-16) be added as subclassifiation reference?

**Comment by d97hah** [comment]
I'll add the ref

2016-12-09 12:06 GMT+01:00 Robert Forkel <notifications@github.com>:
