### ISSUE TITLE
Changing a languoid name through-the-web

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog#4]
Navigate to the info file of the languoid for which you want to change the name, then ...

![gl_changename_1](https://cloud.githubusercontent.com/assets/870184/12657898/117dbc1a-c606-11e5-82c7-d045805c3864.jpg)

If you are done editing the name, make sure you select the option "Create a new branch" ...

![gl_namechange2](https://cloud.githubusercontent.com/assets/870184/12657903/11b91ada-c606-11e5-8e0d-7ec215923891.jpg)

... which will give you the option to create a [pull request](https://help.github.com/articles/using-pull-requests/), i.e. a proposal to change glottolog data, which can be reviewed by the editors:

![gl_namechange3](https://cloud.githubusercontent.com/assets/870184/12657900/11b4e0b4-c606-11e5-830b-bc6472de6e64.jpg)

**Comment by BishnupriyaMe** [comment]
Footlocker: bish1244 gives Bishnupuriya is not correct. It is Bishnupriya Manipuri. You can verify 
Iso639-3: boy. Hope you will help with the correction.
with http://www-01.sil.org/iso639-3/documentation.asp?id=bpy

**Comment by HedvigS** [comment]
"Bishnupriya Manipuri" is listed as an alternative name of bish1244. You've seen this and want it to be the main name?

**Comment by BishnupriyaMe** [comment]
Sorry auto correct is doing the mess.
Glottolog: bish1244 gives Bishnupuriya is not correct. It is Bishnupriya Manipuri. You can verify with iso639-3:bpy
http://www-01.sil.org/iso639-3/documentation.asp?id=bpy

**Comment by BishnupriyaMe** [comment]
Sorry auto correct is doing the mess.
Glottolog: bish1244 gives Bishnupuriya is not correct. It is Bishnupriya Manipuri. You can verify with iso639-3:bpy
http://www-01.sil.org/iso639-3/documentation.asp?id=bpy

**Comment by HedvigS** [comment]
The way to suggest changes in Glottolog is either to make a new issue (https://github.com/clld/glottolog/issues) or click the alarm bell icon on the relevant page, which in this case takes you here: mailto:glottolog@shh.mpg.de?body=Dear%20Glottolog%20maintainers%2C%0A%0AI%20found%20an%20error%20in%20languoid%20bish1244%3A%20Bishnupuriya.&subject=Error%20in%20Glottolog%20languoid%20bish1244

This thread is not for specific issues like this.

**Comment by BishnupriyaMe** [comment]
Yes there is nothing like Bishnupriya. Full name we call it Bishnupriya Manipuri and in Short Form BPY which is our ISO code. Some nasty people are trying hard to confuse people by terms like Bishnupuriya in some webs. I am a speaker of this endangered language. If you want to verify I can guide to the president of Mahasabha of our community. Thanks for the correction in advance.

**Comment by d97hah** [comment]
A PR for this change (to Bishnupriya Manipuri) has already been issued and
merged but it won't appear on glottolog.org until the next version. Hold
your horses...

2017-08-29 2:55 GMT+02:00 BishnupriyaMe <notifications@github.com>:

**Comment by BishnupriyaMe** [comment]
Thanks HedvigS.
click the alarm bell icon on the relevant page, which in this case takes you "here"-> I clicked. It took me to my mailbox, I composed and send it to glottolog@shh.mpg.de. Hope it will be corrected :)

**Comment by BishnupriyaMe** [comment]
Thanks HedvigS.
click the alarm bell icon on the relevant page, which in this case takes you "here"-> I clicked. It took me to my mailbox, I composed and send it to glottolog@shh.mpg.de. Hope it will be corrected :)

**Comment by BishnupriyaMe** [comment]
Thanks d97hah, will wait for next version. By the way how much time (days) can I expect for next version?

**Comment by bishnupuriya** [comment]
Bishnupuriya is one of the 100 non scheduled language of India published according to Census of India. Bishnupriya Manipuri/Manipuri Bishnupriya is subgroup of Bishnupuriya Language.

**Comment by xflr6** [comment]
https://github.com/clld/glottolog/issues/4#issuecomment-325522184 (bish1244) fixed by 4ff180beb84bb9a55ed48649797b2958328e3f37

Superseded by https://github.com/clld/glottolog/wiki/Changing-a-languoid-name-through-the-web

**Comment by BishnupriyaMe** [comment]
This BISHNUPURIYAS are scammers. You BISNUPURIYA whoever you are don't try mislead GLOTTOLOG. It's an authentic and helping out endangered languages around the word. There is no existence of any community with name BISHNUPURIYA. These puriyas are paid brokers to corrupt an andangered "BISHNUPRIYA MANIPURI" community.
@xrotwang authenticity please check those docs which was upladed and Bishnupriya Manipuri in Wiki also yo can verify. Please weed out this user @bishnupuriya . 

@bishnupuriya  Can you show your origin at Bankura with an existing community at Bankura of West Bengal as your claiming? Provide historical facts.

You people are already caught by the APEX Bishnupriya Manipuri Orgs and you people are driven out. Get lost.
