### ISSUE TITLE
Re-classify Bhatola

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog#40]
[Bhatola](http://glottolog.org/resource/languoid/id/bhat1237) is currently "classified" as Unclassifiable. [ISO says it's nonexistent](http://www-01.sil.org/iso639-3/chg_detail.asp?id=2015-047). Should we move it to Bookkeeping?

**Comment by d97hah** [comment]
Yes, I'll do it.

2016-12-09 9:18 GMT+01:00 Robert Forkel <notifications@github.com>:
