### ISSUE TITLE
Make automated language assignment optional

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog#42]
It should be possible for each reference provider to opt-out of automated language assignment, e.g. in case there are too many false positives. This seems to be the case for `degruyter` and possibly also for `benjamins`.

**Comment by d97hah** [comment]
Agree. They both are collections not primarily of descriptive linguistics
like most of the other biblios, but collections of refs in linguistics in
general hence a higher degree of false positives is to be expected.

2016-12-09 9:52 GMT+01:00 Robert Forkel <notifications@github.com>:

**Comment by xflr6** [comment]
Currently implemented in `glottolog3` import:

https://github.com/clld/glottolog3/blob/dcd6ae1215ae30cde1404f4123c93cbb28bf3206/glottolog3/initdb.py#L374-L392
