### ISSUE TITLE
R's APE library cannot read some glottolog newick files.

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/glottolog#47]
Some of the trees generated by glottolog contain singleton nodes. This is valid according to the `newick` specification but cause the `APE` library in `R` to choke:

e.g. the newick file [here for Damal languages](http://glottolog.org/resource/languoid/id/dama1272.newick.txt) looks like this in NEXUS:

```
#NEXUS
Begin taxa;
dama1272
dama1272
amon1239
amun1245
engg1246
nucl1638
;
end;
Begin trees;
tree damal = ((amon1239:1,amun1245:1,engg1246:1,nucl1638:1)dama1272:1);
end;
```

... but this newick string generates this error: 

```{r}
> tree <- read.nexus("damal.trees")
Error in read.nexus("damal.trees") :
  The tree has apparently singleton node(s): cannot read tree file.
  Reading NEXUS file aborted at tree no.1
```

This problem is discussed in the `APE` [FAQ](http://ape-package.ird.fr/ape_faq.html) and there is a solution posted on the [r-sig-phylo](https://www.mail-archive.com/r-sig-phylo@r-project.org/msg02637.html) mailing list. 

Failing that the newick string can be modified from this:

```
((amon1239:1,amun1245:1,engg1246:1,nucl1638:1)dama1272:1);
```

to this:
```
(amon1239:1,amun1245:1,engg1246:1,nucl1638:1)dama1272:1;
```
... which will work.

**Comment by xrotwang** [comment]
Looking at https://glottolog.org/resource/languoid/id/dama1272.newick.txt the issue seems to be resolved.
