### ISSUE TITLE
Remove TeXisms from gj.bib

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog#76]
`gj.bib` has explicit uppercase markers in it e.g.
>    title =  {{T}ypology of {G}eneric-{P}erson {M}arking in {T}shobdun {R}gyalrong}

as well as chinese content, e.g.
> title = {\zh{夏藏対音資料からみた西夏語の声調} {K}azō taion shiryō kara mita {S}eikago no seichō.}

The uppercase markers should be removed, and the chinese content factored out into separate fields, e.g.
> title_zh = {夏藏対音資料からみた西夏語の声調}

**Comment by d97hah** [comment]
In hh.bib started doing

title_original = {夏藏対音資料からみた西夏語の声調}

then the inlg field should say which language the title_original is
actually in.

Conventions may differ but the rendering of titles in bibliographies is
often
"%s %s [%s]" % (title_original, title, title_english) if title_english else "%s
%s" % (title_original, title)







2017-02-20 11:16 GMT+01:00 Robert Forkel <notifications@github.com>:

**Comment by xrotwang** [comment]
ah ok. Yes, maybe that scales better than my approach. We do have other fields with Chinese content, too, though, in `gj.bib`. Should they be converted in the same way, i.e. have `note_original`?

**Comment by d97hah** [comment]
2017-02-20 12:00 GMT+01:00 Robert Forkel <notifications@github.com>:

> ah ok. Yes, maybe that scales better than my approach. We do have other
> fields with Chinese content, too, though, in gj.bib. Should they be
> converted in the same way, i.e. have note_original?
>
yes, why not. I have used only booktitle_original and title_original so far
since that's demanded by some publishers, but it should really be
throughout.
