### ISSUE TITLE
Bowern bib is missing year often

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog#81]
Entries in `bowern.bib` are missing a `year` field quite often, which makes merging of duplicates difficult. We may want to fix this in the source bibtex.

**Comment by d97hah** [comment]
Doing an imputation of the year by matching title/author with ozbib should
fill in the year safely for a large number of cases.

2017-02-23 20:54 GMT+01:00 Robert Forkel <notifications@github.com>:

**Comment by xrotwang** [comment]
Yeah, I noticed it for a couple of items which have now come in from Benjamins as well.

**Comment by chirila** [comment]
odd, if you give me a list of missing items I can look into it.

**Comment by xrotwang** [comment]
Some of these have been addressed - others will follow in a piece-meal fashion.
