### ISSUE TITLE
Jalkunan

### ISSUE THREAD

**Issue by HeathJeffrey** [clld/glottolog#91]
Jalkunan (Mande, Burkina) is a different language from Jeli. In fact the two are not particularly close grammatically.

A 2017 grammar of Jalkunan on LDH has an appendix discussing this issue.

http://ldh.clld.org/2017/01/01/escidoc2346932/

**Comment by d97hah** [comment]
Thanks Jeffrey that establishes it definitively. There's also Berthelette &
Berthelette (2001) with a wordlist of Jalkunan (but it does not discuss the
relationship with Jeri). all the best, H

Berthelette, John & Carol Berthelette. (2001) Sociolinguistic Survey Report
for the Blé Language. SIL International, Dallas. SIL Electronic Survey
Reports 2001-001

2017-05-19 19:46 GMT+02:00 HeathJeffrey <notifications@github.com>:

**Comment by xflr6** [comment]
These seem to be the corresponding the languoids:
https://github.com/clld/glottolog/blob/master/languoids/tree/mand1469/west2780/mand1431/cent2047/mand1432/jogo1241/jeri1241/jalk1242/md.ini
https://github.com/clld/glottolog/blob/master/languoids/tree/mand1469/west2780/mand1431/cent2047/mand1432/jogo1241/jeri1241/jeri1242/md.ini
Can we close this issue?

**Comment by d97hah** [comment]
Yes they are the two, can be closed.

2017-11-22 11:20 GMT+01:00 Sebastian Bank <notifications@github.com>:
