### ISSUE TITLE
Lezghian

### ISSUE THREAD

**Issue by agricolamz** [clld/glottolog#94]
Isn't it better use Lezgian instead of Lezghian? There is no such a name in any English publication I found.

**Comment by haspelmath** [comment]
Yes indeed.


Martin


Am 31/05/17 um 06:45 schrieb George Moroz:

**Comment by xrotwang** [comment]
See https://github.com/clld/glottolog/pull/95

**Comment by agricolamz** [comment]
Thank you, Robert!
