### ISSUE TITLE
Encoding of the Newick tree is wrong

### ISSUE THREAD

**Issue by Anaphory** [clld/glottolog#96]
The glottolog newick tree file download (http://glottolog.org/static/download/tree-glottolog-newick.txt) appears to have the wrong HTTP headers set. While the file is encoded in UTF-8, the HTTP headers seem to imply no encoding or a different one (my browsers interpret windows-1252, I have not checked the HTTP trace), leading to

    ('Sasi [sasi1238]':1,'Ç‚Hua [huaa1249]':1)

instead of

    (('Sasi [sasi1238]':1,'ǂHua [huaa1249]':1)

when viewed in the browser.

**Comment by xrotwang** [comment]
Adding a directive `charset utf-8;` to our nginx config should fix this.

**Comment by xflr6** [comment]
Thanks, fixed via 8273dfe2e7d542f9d2c1a5dbcad74ef4b77e2785.
