### ISSUE TITLE
Nukuria

### ISSUE THREAD

**Issue by lannin** [clld/glottolog#97]
Some addings to Nukuria bibliography:
https://catalog.hathitrust.org/Record/001683841 G. Friederici 1912 Beiträge zur Völker- und Sprachenkunde von Deutsch-Neuguinea// Wissenschaftliche Ergebnisse einer amtlichen Forschungsreise nach dem Bismarck-Archipel im Jahre 1908. Mitt. a. d. Deutschen Schutzgebieten. Ergänzungsheft Nr. 5. Berlin.
sealang.net/archives/pl/pdf/PL-C39.441.pdf Lithgow, D.R. 1976 "Austronesian Languages: Milne Bay and Adjacent Islands (Milne Bay Province)"// Wurm, S.A. editor, New Guinea area languages and language study, Vol. 2, Austronesian languages.
C-39:441-526. Pacific Linguistics, The Australian National University. DOI:10.15144/PL-C39.441

**Comment by d97hah** [comment]
Thanks, which volume of Friederici talks about Nukuria?

2017-06-13 14:59 GMT+02:00 lannin <notifications@github.com>:

**Comment by lannin** [comment]
In volume 2, short wordlist on p. 302-303 and small ethnographic descriptions on p. 299-303 (and also about other outliers)

**Comment by d97hah** [comment]
Thanks I seem to have only photocopied to p 227. I will fix the glottolog
ref accordingly. Do you have a pdf of the full volume? Thanks, H

2017-06-14 7:41 GMT+02:00 lannin <notifications@github.com>:

**Comment by lannin** [comment]
No, I've not but it is possible to obtain from the link on hathitrust (if you have USA IP). If you want I can download it but not today.

**Comment by d97hah** [comment]
It also ask for a partner login, so when/if you do have access to a pdf, do
pass it on. Thanks, H

2017-06-14 15:50 GMT+02:00 lannin <notifications@github.com>:

**Comment by chirila** [comment]
I have partner access - send me the exact link for what you need and I can download it.
C

Claire Bowern
Associate Professor
Director of Graduate Studies
Department of Linguistics
Yale University
Dow Hall, 370 Temple St
New Haven, CT  06511

**Comment by d97hah** [comment]
This one:
https://babel.hathitrust.org/cgi/pt?id=uc1.c2792613

Thanks,
H

2017-06-14 22:30 GMT+02:00 Claire Bowern <notifications@github.com>:

> I have partner access - send me the exact link for what you need and I can
> download it.
> C
>
> Claire Bowern
> Associate Professor
> Director of Graduate Studies
> Department of Linguistics
> Yale University
> Dow Hall, 370 Temple St
> New Haven, CT 06511
>

**Comment by chirila** [comment]
https://www.dropbox.com/s/gkhum7me0r6sm2b/uc1.c2792613-1497510350.pdf?dl=0

**Comment by d97hah** [comment]
Got it, thanks very mucho!!

2017-06-15 10:45 GMT+02:00 Claire Bowern <notifications@github.com>:

> https://www.dropbox.com/s/gkhum7me0r6sm2b/uc1.c2792613-1497510350.pdf?dl=0
>
>
>

**Comment by xflr6** [comment]
Fixed in https://github.com/clld/glottolog/commit/4a4220d60d5bfbb97491e790488d95a39cd9d94d#diff-da217050127f79815921cdbdd55502b4
