### ISSUE TITLE
Chinook

### ISSUE THREAD

**Issue by Taivo55** [clld/glottolog#99]
Kiksht is listed as a dialect of Chinook (chin1286, chh), but it is actually a synonym for Wasco-Wishram (wasc1239, wac).  See, for example, Marianne Mithun.  1999.  _The Languages of Native North America_ (Cambridge).  Page 382

**Comment by d97hah** [comment]
Thanks, will fix that for next version!

2017-06-24 6:40 GMT+02:00 Taivo55 <notifications@github.com>:

**Comment by xflr6** [comment]
Fixed by 450d2de454e059014f4f6b0b8a9e3bf57e83fbaf
